[theme]
base = "dark"
primaryColor = "#4F46E5"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#111827"
textColor = "#E5E7EB"

[server]
# Increase max upload size (MB) to accommodate many images
maxUploadSize = 2000
